packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.4.1
    '@nuxt/eslint': ^1.4.1
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.0
    '@unocss/eslint-config': ^66.1.2
    '@unocss/nuxt': ^66.1.2
    '@vite-pwa/nuxt': ^1.0.1
    '@vueuse/nuxt': ^13.2.0
    nuxt: ^3.17.4
    unocss: ^66.1.2
    unplugin: ^2.3.4
    vite: ^6.3.5

  dev:
    '@antfu/eslint-config': ^4.13.1
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10

  frontend:
    '@vueuse/core': ^13.2.0
    pinia: ^3.0.2
    vue: ^3.5.14

  icons:
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/twemoji': ^1.2.2

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
